openapi: 3.0.0
info:
  title: Passenger Management System (PASMAS)
  description: TODO
  version: "0.1"
servers:
  - url: http://localhost:8080

paths:
  /api/passenger:
    $ref: "paths/api/passenger/passenger.yaml"
  /api/passenger/{id}:
    $ref: "paths/api/passenger/{id}_passenger.yaml"
  /realtime/passenger:
    $ref: "paths/realtime/passenger.yaml"

components:
  schemas:
    SuccessResponse:
      $ref: "models/responses/successResponse.yaml"
    ErrorResponse:
      $ref: "models/responses/errorResponse.yaml"

    Division:
      $ref: "models/division/division.yaml"

    PassengerStructSelect:
      $ref: "models/passenger/passenger_struct_select.yaml"
    PassengerStructInsert:
      $ref: "models/passenger/passenger_struct_insert.yaml"
    PassengerStructUpdate:
      $ref: "models/passenger/passenger_struct_update.yaml"