openapi: 3.0.0
info:
  title: Passenger Management System (PASMAS)
  description: TODO
  version: "0.1"
servers:
  - url: http://localhost:8080

paths:
  /api/passenger:
    $ref: "paths/api/passenger.yaml"

components:
  schemas:
    SuccessResponse:
      $ref: "docs/openapi/models/responses/successResponse.yaml"
    ErrorResponse:
      $ref: "docs/openapi/models/responses/errorResponse.yaml"

    PassengerStructSelect:
        $ref: "docs/openapi/models/passenger/passenger_struct_select.yaml"
    PassengerStructInsert:
        $ref: "docs/openapi/models/passenger/passenger_struct_insert.yaml"
    PassengerStructUpdate:
        $ref: "docs/openapi/models/passenger/passenger_struct_update.yaml"


  responses:
    DefaultSuccessResponse:
      description: Standardantwort für erfolgreiche Operationen
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SuccessResponse"
    DefaultErrorResponse:
      description: Standardantwort für Fehlerzustände
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'