openapi: 3.0.0
info:
  title: Passenger Management System (PASMAS)
  description: TODO
  version: "0.1"
servers:
  - url: http://localhost:8080

paths:
  /api/passenger:
    $ref: "paths/api/passenger.yaml"

components:
  schemas:
    SuccessResponse:
      $ref: "models/response.yaml#/SuccessResponse"
    ErrorResponse:
      $ref: "models/response.yaml#/ErrorResponse"
    Passenger:
      $ref: "models/passenger.yaml"
    Division:
      $ref: "models/division.yaml"
