services:
  database:
    image: postgres
    hostname: ${DATABASE_HOSTNAME}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger:
    build: ../docs/openapi
    container_name: swagger
    ports:
      - 8000:8080

  backend:
    build: ../src
    container_name: golang
    ports:
      - 8080:8080
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
